// English sidebar labels for slide steps.
//
// Topic and sub-topic headings stay FRENCH (Le Présent, L'Impératif, Le Subjonctif…)
// — only the numbered sub-divisions beneath them are translated.
//
// La Lettre (Section B) is excluded at the call site, not here: its steps are already
// English and its structure is different.
//
// Anything absent from this map falls through unchanged, so a new French step name
// simply shows as-is rather than breaking.
module.exports = {
  // ---- the 8-step spine (49 sub-topics each) ----
  'Description': 'Description',
  'Formation': 'How to Form',
  'Exceptions': 'Exceptions',
  'Pièges': 'Common Mistakes',
  'Exemples': 'Examples',
  'En contexte': 'In Context',
  'Pratique QCM': 'MCQ Practice',
  'Pratique — à compléter': 'Fill-in-the-blanks Practice',

  // ---- topic-level usage stacks ----
  'Usages': 'Usage',
  'Mémo visuel': 'Visual Memory Aid',
  'En application': 'In Practice',
  'Galerie visuelle': 'Visual Gallery',

  // ---- recurring section slides ----
  'Tableau de référence': 'Reference Table',
  'Examen CBSE': 'CBSE Exam',
  'Check-list': 'Checklist',
  'Cartes mémoire': 'Flashcards',
  'Bienvenue': 'Welcome',
  'Les 8 étapes': 'The 8 Steps',
  'Les 3 groupes': 'The 3 Groups',
  'La ligne du temps': 'Timeline',
  'Laboratoire de conjugaison': 'Conjugation Lab',
  'Examen CBSE — tous les temps': 'CBSE Exam — All Tenses',
  'Check-list de l’examen': 'Exam Checklist',
  'Arbre de décision': 'Decision Tree',
  'Pourquoi mélanger': 'Why Mix Them',
  'Identifier le sujet': 'Identify the Topic',
  'Mélange 1 — QCM': 'Mixed 1 — MCQ',
  'Mélange 2 — à compléter': 'Mixed 2 — Fill in the Blanks',
  'Les pièges les plus coûteux': 'The Costliest Traps',
  'Stratégie de l’examen': 'Exam Strategy',
  'Bonne chance': 'Good Luck',

  // ---- "Usages · X" sub-divisions, by their French qualifier ----
  'Usages · La routine': 'Usage: Daily Routine',
  'Usages · Maintenant': 'Usage: Happening Now',
  'Usages · Vérités générales': 'Usage: General Truths',
  'Usages · Les instructions': 'Usage: Instructions',
  'Usages · Conseils & invitations': 'Usage: Advice & Invitations',
  'Usages · La description': 'Usage: Description & Background',
  'Usages · L’habitude passée': 'Usage: Past Habits',
  'Usages · L’action interrompue': 'Usage: Interrupted Action',
  'Usages · L’événement terminé': 'Usage: A Completed Event',
  'Usages · La suite d’actions': 'Usage: A Sequence of Actions',
  'Usages · Le résultat présent': 'Usage: Present Result',
  'Usages · Le passé du passé': 'Usage: The Past Before the Past',
  'Usages · Le regret & l’explication': 'Usage: Regret & Explanation',
  'Usages · Projets & prédictions': 'Usage: Plans & Predictions',
  'Usages · Promesses & conseils': 'Usage: Promises & Advice',
  'Usages · Après quand & dès que': 'Usage: After quand & dès que',
  'Usages · Fini avant un moment futur': 'Usage: Finished Before a Future Moment',
  'Usages · La supposition': 'Usage: Supposition',
  'Usages · La politesse': 'Usage: Politeness',
  'Usages · L’hypothèse': 'Usage: Hypotheses',
  'Usages · Conseils & nouvelles': 'Usage: Advice & News',
  'Usages · La routine quotidienne': 'Usage: Daily Routine',
  'Usages · Le sens réciproque': 'Usage: Reciprocal Meaning',
  'Usages · Volonté & Désir': 'Usage: Will & Desire',
  'Usages · L’Émotion': 'Usage: Emotion',
  'Usages · La Nécessité': 'Usage: Necessity',
  'Usages · Doute & Négation': 'Usage: Doubt & Negation',
  'Usages · Les conjonctions déclencheurs': 'Usage: Trigger Conjunctions',
  'Usages · Refuser & démentir': 'Usage: Refusing & Denying',
  'Usages · La fréquence zéro': 'Usage: Never — Zero Frequency',
  'Usages · Ce qui a changé': 'Usage: What Has Changed',
  'Usages · Zéro chose': 'Usage: Nothing — Zero Things',
  'Usages · Zéro personne': 'Usage: Nobody — Zero People',
  'Usages · La restriction': 'Usage: Only — Restriction',
  'Usages · Refuser deux choses': 'Usage: Refusing Two Things',
  'Usages · Éviter la répétition': 'Usage: Avoiding Repetition',
  'Usages · À qui on parle': 'Usage: Who You Speak To',
  'Usages · Le lieu où l’on va': 'Usage: Where You Go',
  'Usages · Les quantités': 'Usage: Quantities',
  'Usages · Insister & après une préposition': 'Usage: Emphasis & After a Preposition',
  'Usages · Deux pronoms ensemble': 'Usage: Two Pronouns Together',
  'Usages · Décrire qui fait l’action': 'Usage: Describing Who Acts',
  'Usages · Décrire ce qu’on subit': 'Usage: Describing What Receives',
  'Usages · Le lieu et le moment': 'Usage: Place & Time',
  'Usages · Quand le verbe demande DE': 'Usage: When the Verb Needs DE',
  'Usages · Après une préposition': 'Usage: After a Preposition',
  'Usages · Rapporter une affirmation': 'Usage: Reporting a Statement',
  'Usages · Rapporter une question': 'Usage: Reporting a Question',
  'Usages · Rapporter un ordre': 'Usage: Reporting an Order',
  'Usages · Quand le verbe introducteur est au passé': 'Usage: When the Reporting Verb Is Past',
  'Usages · Les repères de temps changent': 'Usage: Time Markers Change',
  'Usages · La question passe-partout': 'Usage: The All-Purpose Question',
  'Usages · Le registre formel': 'Usage: The Formal Register',
  'Usages · Une personne ou une chose': 'Usage: A Person or a Thing',
  'Usages · Demander les circonstances': 'Usage: Asking About Circumstances',
  'Usages · Choisir dans un ensemble': 'Usage: Choosing From a Set',
  'Usages · Demander une quantité': 'Usage: Asking How Many',
  'Usages · Présenter ce qui est à soi': 'Usage: Saying What Is Yours',
  'Usages · Comparer sans répéter': 'Usage: Comparing Without Repeating',
  'Usages · Montrer du doigt': 'Usage: Pointing at Things',
  'Usages · Celui de, celui qui': 'Usage: celui de, celui qui',
  'Usages · Celui-ci ou celui-là': 'Usage: celui-ci or celui-là'
};
