#!/bin/bash
# Assemble master-grammar-app.html from parts.
# Reveal.js CSS = line 17, Reveal.js JS bundle = line 869 of the original verbs deck.
set -e
PROJ="C:/claude/10 th"
SRC="$PROJ/Les Verbes - Tous les Temps.html"
OUT="$PROJ/master-grammar-app.html"
SP="C:/claude/10 th/build-system"

# Content parts, in deck order. Add new topic files here.
PARTS=(
  t0-timeline.html
  c1-verbes.html c2-verbes.html c3-verbes.html c4-verbes.html t-nom.html c5-verbes.html
  u-verbes-usage.html u-verbes-filmscene.html
  t2-subjonctif.html t2b-subjonctif.html u-subjonctif-usage.html
  t3a-negation.html t3b-negation.html u-negation-usage.html
  t4-pronoms.html t4b-pronoms.html u-pronoms-usage.html
  t5-relatifs.html t5b-relatifs.html u-relatifs-usage.html
  t6-discours.html t6b-discours.html u-discours-usage.html
  t7-question.html t7b-question.html u-question-usage.html
  t8-possessifs.html u-possessifs-usage.html
  t9-demonstratifs.html u-demonstratifs-usage.html
  t-conjlab.html
  t11-lettre.html
  t12-messages.html
  t13-lecons.html
  t10-revision.html
)

# La Lettre slides are generated from letterdata.js
node "$SP/gen-letter-slides.js"

# La Nominalisation slides are generated from nomdata.js
node "$SP/gen-nom-slides.js"
node "$SP/gen-message-slides.js"

# Les Lecons slides are generated from the 10th-lessons content files
node "$SP/gen-lecon-slides.js"

cat "$SP/a-head.html" > "$OUT"
sed -n '17p' "$SRC" >> "$OUT"
cat "$SP/b-style.html" >> "$OUT"
for p in "${PARTS[@]}"; do
  [ -f "$SP/$p" ] && cat "$SP/$p" >> "$OUT"
done
# 500-verb conjugation dataset, generated by extract-verbs.js (its own script block;
# top-level `const` is visible to the engine script that follows)
if [ -f "$SP/verbdata.js" ]; then
  echo '<script>' >> "$OUT"
  cat "$SP/verbdata.js" >> "$OUT"
  echo '</script>' >> "$OUT"
fi
# Letter-module dataset (assembled by the _lessons/_letters/_practice sources)
cat "$SP/d-mid.html" >> "$OUT"
sed -n '869p' "$SRC" >> "$OUT"
cat "$SP/e-engine.html" >> "$OUT"

# Inline @@PHOTO:id@@ tokens as base64 data URIs (keeps the output offline-capable)
# Splice Usage slides in after each Description slide (additive; sources untouched)
node "$SP/insert-usages.js"

# Lesson photos: downloaded once into vendor/, downscaled, embedded as data: URIs
# so the shipped file still makes zero network requests.
node "$SP/inline-lecon-photos.js"

node "$SP/inline-photos.js"


# Inline the last external deps (Google Fonts, GSAP, Lucide) -> zero network requests
node "$SP/inline-assets.js"

# Publish the deployable artifact for GitHub Pages (docs/ publishing root)
mkdir -p "$PROJ/docs"
cp "$OUT" "$PROJ/docs/index.html"
touch "$PROJ/docs/.nojekyll"

# The vocabulary app is built by its own project; copy the finished file in so the
# topbar link resolves. Conditional on purpose: this build must not fail because a
# separate project moved.
LECONS="C:/10th lessons/lecons.html"
if [ -f "$LECONS" ]; then cp "$LECONS" "$PROJ/docs/lecons.html";
else echo "  note: $LECONS not found - docs/lecons.html left as-is"; fi

# Firebase clone -> docs/app.html. Post-processing: it READS the finished
# docs/index.html and writes a second file, so the offline deck is untouched.
node "$SP/make-firebase-clone.js"

echo "bytes: $(wc -c < "$OUT")"
echo "stacks: $(grep -c 'data-sub=' "$OUT")"
echo "slides: $(grep -c 'data-slide-id=' "$OUT")"
