// Build nomdata.js from the source list of nominal forms.
//
// Source: C:/claude/10th 2/verbs to noun/list-of-nominal-forms.md
//   - French pairs first, then the English pairs in the SAME order.
//   - Strips the coaching-centre header, bullets, and stray line numbers
//     glued into six entries (11 chanter, 15 créer, 17 déjeuner, 39 fumer,
//     73 retourner, 77 se promener).
//   - Applies the corrections listed in CORRECTIONS below; each one is carried
//     onto the slide as a visible note so nothing is changed silently.
const fs = require('fs');
const path = require('path');

const SRC = 'C:/claude/10th 2/verbs to noun/list-of-nominal-forms.md';

/* verb -> { noun?, gender?, en?, note } — every change is recorded and shown */
const CORRECTIONS = {
  'moissonner': { noun: 'la moisson', en: 'to harvest → harvest',
    note: 'La source écrit « la mousson » — mais la mousson, c\u2019est le monsoon. La récolte, c\u2019est la moisson.' },
  'disparaître': { noun: 'la disparition',
    note: 'La source écrit « la disparation », qui n\u2019existe pas. La forme correcte est la disparition.' },
  'habiter': { gender: 'f',
    note: 'La source marque « (m) » — mais habitation est un nom féminin : l\u2019habitation.' },
  'favoriser': { noun: 'la favorisation', en: 'to favour → favouring',
    note: 'La source donne « la faveur » (a favour). La forme nominale du verbe favoriser est la favorisation.' },
  'devoir': { en: 'to have to \u2192 duty',
    note: 'La traduction source « to duty » n\u2019est pas de l\u2019anglais correct.' }
};

const raw = fs.readFileSync(SRC, 'utf8').replace(/\r/g, '');
const lines = raw.split('\n').map(l => l.trim()).filter(Boolean)
  .filter(l => !/^#/.test(l))
  .filter(l => !/frenchcoaching|NIT Faridabad|Contacts:/i.test(l))
  .filter(l => !/^List of nominal forms$/i.test(l));

const frRaw = [], enRaw = [];
lines.forEach(l => {
  const t = l.replace(/^-\s*/, '').replace(/^\d+\s+/, '').trim();
  if (!t) return;
  (/^to\s/i.test(t) ? enRaw : frRaw).push(t);
});

if (frRaw.length !== enRaw.length) {
  console.error(`FAIL: ${frRaw.length} French vs ${enRaw.length} English entries — cannot align`);
  process.exit(1);
}

/* "accepter - l'acceptation (f)"  ->  verb / noun / gender */
const splitPair = s => {
  const parts = s.split(/\s*[-\u2013]\s*/);          // hyphen or en-dash
  const verb = parts.shift().trim().replace(/[.\s]+$/, '');
  let rest = parts.join(' - ').trim().replace(/[.\s\u2013-]+$/, '');
  let gender = '';
  const g = rest.match(/\(([mf])\)\s*$/i);
  if (g) { gender = g[1].toLowerCase(); rest = rest.slice(0, g.index).trim(); }
  if (!gender) {                                      // infer from the article
    if (/^la\s|^une\s/.test(rest)) gender = 'f';
    else if (/^le\s|^un\s/.test(rest)) gender = 'm';
  }
  return { verb, noun: rest, gender };
};

const data = frRaw.map((fr, i) => {
  const { verb, noun, gender } = splitPair(fr);
  const enParts = enRaw[i].split(/\s*[-\u2013]\s*/);
  const enVerb = (enParts.shift() || '').trim();
  const enNoun = enParts.join(' - ').trim().replace(/^the\s+/i, '');
  const rec = { verb, noun, gender, en: `${enVerb} \u2192 ${enNoun}` };

  const c = CORRECTIONS[verb];
  if (c) {
    if (c.noun)   rec.noun   = c.noun;
    if (c.gender) rec.gender = c.gender;
    if (c.en)     rec.en     = c.en;
    rec.note = c.note;
  }
  return rec;
});

/* ---- self-checks: fail loudly rather than ship a broken list ---- */
const problems = [];
if (data.length !== frRaw.length) problems.push('lost entries during parse');
data.forEach((d, i) => {
  if (!d.verb)  problems.push(`#${i}: no verb`);
  if (!d.noun)  problems.push(`#${i} ${d.verb}: no noun`);
  if (!d.en || /\u2192\s*$/.test(d.en)) problems.push(`#${i} ${d.verb}: no English`);
  if (!/^(la|le|l\u2019|l'|un|une)\s|^l\u2019|^l'/.test(d.noun)) problems.push(`#${i} ${d.verb}: noun has no article — "${d.noun}"`);
  if (/\d/.test(d.verb + d.noun)) problems.push(`#${i} ${d.verb}: stray digit survived`);
});
/* flip-card keys are `data-sub + "::" + front text` — identical fronts collide */
const seen = new Map();
data.forEach((d, i) => {
  if (seen.has(d.verb)) problems.push(`duplicate verb "${d.verb}" (#${seen.get(d.verb)} and #${i}) — flip-card keys would collide`);
  else seen.set(d.verb, i);
});
Object.keys(CORRECTIONS).forEach(v => {
  if (!data.some(d => d.verb === v)) problems.push(`correction target "${v}" not found in the source`);
});

if (problems.length) {
  console.error('PROBLEMS:');
  problems.forEach(p => console.error('  ' + p));
  process.exit(1);
}

fs.writeFileSync(path.join(__dirname, 'nomdata.js'),
  '/* Nominal forms dataset — generated by gen-nomdata.js from the source list.\n' +
  '   Do not hand-edit; edit the source list or the CORRECTIONS map instead. */\n' +
  'const NOMDATA = ' + JSON.stringify(data) + ';\n');

console.log(`pairs: ${data.length}`);
console.log(`corrections applied: ${data.filter(d => d.note).length}`);
console.log(`gendered: ${data.filter(d => d.gender).length}/${data.length}`);
console.log('nomdata.js written — self-checks clean');
